fragment PrisonerItem on Prisoner {
  id
  article
  prisonerData {
    birthdate
    city
    dateofarrest
    description
    fieldGroupName
    freedomdate
    name
    mailinterests
    sex
    status
  }
  featuredImage {
    node {
      mediaItemUrl
    }
  }
}

query prisoners {
  prisoners {
    edges {
      node {
        ...PrisonerItem
      }
    }
  }
}
