query prisonerStatusCounts {
  prisoner_statsCollection {
    edges {
      node {
        id
        total_count
        in_process_count
        imprisoned_count
        address_count
        out_count
        age_ranges
        created_at
        updated_at
      }
    }
  }
}
