query prisonerStatusCounts {
  prisonerStatusCounts {
    outCount
    totalCount
    inProcessCount
    addressCount
    ageRanges {
      ageRange
      male
      female
    }
    imprisonedCount
  }
}
