fragment PrisonerItem on Prisoner {
  id
  article
  content
  prisonerData {
    addressparsed
    coordinatesparsed
    institutionshortnameparsed
    birthdate
    city
    dateofarrest
    description
    fieldGroupName
    freedomdate
    name
    mailinterests
    sex
    status
  }
  featuredImage {
    node {
      mediaItemUrl
    }
  }
}

query prisoners($offset: Int, $filter: RootQueryToPrisonerConnectionWhereArgs) {
  prisoners(first: $offset, where: $filter) {
    edges {
      node {
        ...PrisonerItem
      }
    }
  }
}
